import type { WidgetDefinition } from "./types"

export const DASHBOARD_WIDGET_REGISTRY: WidgetDefinition[] = [
  {
    id: "kpi-cluster",
    title: "KPI Cluster",
    subtitle: "Views, subscribers, hours, revenue",
    category: "core",
    defaultSize: "half",
    minSize: "quarter",
    maxSize: "full",
    headerColor: "#C9F830",
    iconRailColor: "#FFE357",
    dependency: ["youtube_analytics_v2"],
    status: "ready",
  },
  {
    id: "channel-overview",
    title: "Channel Overview",
    subtitle: "Avatar and identity state",
    category: "core",
    defaultSize: "quarter",
    minSize: "quarter",
    maxSize: "half",
    headerColor: "#FF83EA",
    iconRailColor: "#FFB570",
    dependency: ["youtube_data_v3"],
    status: "ready",
  },
  {
    id: "mini-calendar",
    title: "Mini Calendar",
    subtitle: "2-week calendar heat",
    category: "core",
    defaultSize: "quarter",
    minSize: "quarter",
    maxSize: "half",
    headerColor: "#FFB570",
    iconRailColor: "#FFD8A8",
    dependency: ["none"],
    status: "ready",
  },
  {
    id: "task-stack",
    title: "Task Stack",
    subtitle: "Today queue",
    category: "core",
    defaultSize: "quarter",
    minSize: "quarter",
    maxSize: "half",
    headerColor: "#FFB570",
    iconRailColor: "#FFD8A8",
    dependency: ["none"],
    status: "ready",
  },
  {
    id: "quick-actions",
    title: "Quick Actions",
    subtitle: "Primary navigation launchers",
    category: "core",
    defaultSize: "full",
    minSize: "half",
    maxSize: "full",
    headerColor: "#4FFF5B",
    iconRailColor: "#B9FFBE",
    dependency: ["none"],
    status: "ready",
  },
  {
    id: "recent-uploads",
    title: "Recent Uploads",
    subtitle: "Latest 3 videos",
    category: "analytics",
    defaultSize: "third",
    minSize: "quarter",
    maxSize: "half",
    headerColor: "#579AFF",
    iconRailColor: "#BBD4FF",
    dependency: ["youtube_data_v3", "youtube_analytics_v2"],
    status: "ready",
  },
  {
    id: "top-performer",
    title: "Top Performer",
    subtitle: "Best view leader",
    category: "analytics",
    defaultSize: "third",
    minSize: "quarter",
    maxSize: "half",
    headerColor: "#FF83EA",
    iconRailColor: "#FFB3F0",
    dependency: ["youtube_analytics_v2"],
    status: "ready",
  },
  {
    id: "upload-cadence",
    title: "Upload Cadence",
    subtitle: "14-day consistency pulse",
    category: "analytics",
    defaultSize: "third",
    minSize: "quarter",
    maxSize: "half",
    headerColor: "#40C6E9",
    iconRailColor: "#99E5F5",
    dependency: ["youtube_data_v3"],
    status: "ready",
  },
  {
    id: "alerts-feed",
    title: "Alerts Feed",
    subtitle: "Operational highlights",
    category: "system",
    defaultSize: "half",
    minSize: "quarter",
    maxSize: "full",
    headerColor: "#FF1744",
    iconRailColor: "#FFE357",
    dependency: ["none"],
    status: "ready",
  },
  {
    id: "sync-connection",
    title: "Sync + Connection",
    subtitle: "Auth and sync telemetry",
    category: "system",
    defaultSize: "third",
    minSize: "quarter",
    maxSize: "half",
    headerColor: "#4FFF5B",
    iconRailColor: "#24D3FF",
    dependency: ["youtube_data_v3"],
    status: "ready",
  },
  {
    id: "ai-prompt-box",
    title: "AI Prompt Box",
    subtitle: "Fast strategy asks",
    category: "ai",
    defaultSize: "third",
    minSize: "quarter",
    maxSize: "half",
    headerColor: "#40C6E9",
    iconRailColor: "#579AFF",
    dependency: ["none"],
    status: "prototype",
  },
  {
    id: "revenue-momentum",
    title: "Revenue Momentum",
    subtitle: "4-week pulse",
    category: "analytics",
    defaultSize: "third",
    minSize: "quarter",
    maxSize: "half",
    headerColor: "#C9F830",
    iconRailColor: "#FFB570",
    dependency: ["youtube_analytics_v2"],
    status: "ready",
  },
  {
    id: "superfan-card",
    title: "Superfan Card",
    subtitle: "Community spotlight",
    category: "community",
    defaultSize: "quarter",
    minSize: "quarter",
    maxSize: "half",
    headerColor: "#FF3399",
    iconRailColor: "#FFE357",
    dependency: ["none"],
    status: "prototype",
  },
  {
    id: "system-micro-stack",
    title: "System Micro Stack",
    subtitle: "Storage, model, mode badges",
    category: "system",
    defaultSize: "quarter",
    minSize: "quarter",
    maxSize: "half",
    headerColor: "#00D2FF",
    iconRailColor: "#FFB570",
    dependency: ["none"],
    status: "ready",
  },
  {
    id: "consistency-heatmap",
    title: "Consistency Heatmap",
    subtitle: "30-day activity trend",
    category: "analytics",
    defaultSize: "half",
    minSize: "quarter",
    maxSize: "full",
    headerColor: "#4FFF5B",
    iconRailColor: "#B9FFBE",
    dependency: ["youtube_data_v3"],
    status: "ready",
  },
  {
    id: "goals-tracker",
    title: "Goals Tracker",
    subtitle: "Milestones and targets",
    category: "core",
    defaultSize: "half",
    minSize: "quarter",
    maxSize: "full",
    headerColor: "#C9F830",
    iconRailColor: "#FFE357",
    dependency: ["none"],
    status: "ready",
  },
  {
    id: "alerts-ticker",
    title: "Alerts Ticker",
    subtitle: "Real-time system updates",
    category: "system",
    defaultSize: "full",
    minSize: "quarter",
    maxSize: "full",
    headerColor: "#FF1744",
    iconRailColor: "#FFE357",
    dependency: ["none"],
    status: "ready",
  },
]

export const DEFAULT_DASHBOARD_WIDGET_ORDER = DASHBOARD_WIDGET_REGISTRY.map((widget) => widget.id)

export const DASHBOARD_WIDGET_BY_ID = Object.fromEntries(
  DASHBOARD_WIDGET_REGISTRY.map((widget) => [widget.id, widget]),
)
