import { getDashboardWidgetPaletteColors } from "../../styles/toolboxPalette"
import type { WidgetDefinition } from "./types"

export const DASHBOARD_WIDGET_REGISTRY: WidgetDefinition[] = [
  {
  id: "kpi-cluster",
  title: "Channel Overview",
  subtitle: "Subscribers, views, hours, revenue, CTR, AVD",
  category: "core",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "tall",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(0),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "channel-overview",
  title: "Social Channels",
  subtitle: "Cross-platform follower counts",
  category: "core",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(1),
  dependency: ["youtube_data_v3"],
  status: "ready",
 },
 {
  id: "mini-calendar",
  title: "Mini Calendar",
  subtitle: "2-week calendar heat",
  category: "core",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(2),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "task-stack",
  title: "Task Stack",
  subtitle: "Today queue",
  category: "core",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(3),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "quick-actions",
  title: "Quick Actions",
  subtitle: "Primary navigation launchers",
  category: "core",
  defaultSize: "full",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(4),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "recent-uploads",
  title: "Recent Uploads",
  subtitle: "Latest 3 videos",
  category: "analytics",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(5),
  dependency: ["youtube_data_v3", "youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "top-performer",
  title: "Top Performer",
  subtitle: "Best view leader",
  category: "analytics",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(6),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "alerts-feed",
  title: "Alerts Feed",
  subtitle: "Operational highlights",
  category: "system",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(7),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "ai-prompt-box",
  title: "AI Prompt Box",
  subtitle: "Fast strategy asks",
  category: "ai",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(8),
  dependency: ["none"],
  status: "prototype",
 },
 {
  id: "revenue-momentum",
  title: "Revenue Momentum",
  subtitle: "4-week pulse",
  category: "analytics",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(9),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "superfan-card",
  title: "Superfan Card",
  subtitle: "Community spotlight",
  category: "community",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(10),
  dependency: ["none"],
  status: "prototype",
 },
 {
  id: "system-micro-stack",
  title: "Settings",
  subtitle: "System, sync & mode controls",
  category: "system",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(11),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "consistency-heatmap",
  title: "Upload Cadence",
  subtitle: "30-day activity heat",
  category: "analytics",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(12),
  dependency: ["youtube_data_v3"],
  status: "ready",
 },
 {
  id: "goals-tracker",
  title: "Goals Tracker",
  subtitle: "Milestones and targets",
  category: "core",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(13),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "alerts-ticker",
  title: "News Ticker",
  subtitle: "Real-time system updates",
  category: "system",
  defaultSize: "full",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(14),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "tag-generator",
  title: "Tag Generator",
  subtitle: "AI SEO tag generator",
  category: "creation",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(15),
  dependency: ["youtube_data_v3", "gemini_api"],
  status: "ready",
 },
 {
  id: "revenue-chart",
  title: "Revenue Tracker",
  subtitle: "Weekly grouped ad revenue",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(16),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "community-post",
  title: "Community Post",
  subtitle: "Draft and create posts",
  category: "creation",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "tall",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(17),
  dependency: ["youtube_data_v3", "gemini_api"],
  status: "ready",
 },
 {
  id: "thumb-ai",
  title: "Thumb AI",
  subtitle: "Generate and analyze thumbnails",
  category: "creation",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(18),
  dependency: ["gemini_api"],
  status: "ready",
 },
 {
  id: "description-editor",
  title: "Description Editor",
  subtitle: "Write and template video descriptions",
  category: "creation",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(19),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "realtime-performance",
  title: "Realtime",
  subtitle: "Stats from last 48hr and 60m",
  category: "analytics",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(20),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "keyword-engine",
  title: "Keyword Engine",
  subtitle: "Top keywords by view yield",
  category: "analytics",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(21),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "keyword-overlap-intelligence",
  title: "Keyword Overlap",
  subtitle: "Venn map of title keyword value",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "tall",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(22),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "publish-momentum",
  title: "Published Momentum",
  subtitle: "2D Heatmap of publish times",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(23),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "traffic-sources",
  title: "Traffic Sources",
  subtitle: "Origin of viewership",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(24),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "audience-retention",
  title: "Retention Dip",
  subtitle: "Audience hold graph",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(25),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "shorts-vs-long",
  title: "Long vs Short",
  subtitle: "Shorts vs Long comparative",
  category: "analytics",
  defaultSize: "quarter",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(26),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "comment-replier",
  title: "Comment Responder",
  subtitle: "View, reply & provoke engagement",
  category: "community",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "tall",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(27),
  dependency: ["youtube_data_v3", "gemini_api"],
  status: "ready",
 },
 {
  id: "reach-funnel",
  title: "Reach Funnel",
  subtitle: "Impressions to CTR conversion",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(28),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "relative-retention-benchmark",
  title: "Algo Benchmark",
  subtitle: "Relative performance vs Platform",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(29),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "ad-stack-intelligence",
  title: "The Ad Stack",
  subtitle: "Gross Rev, Monetized Playbacks, CPM",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(30),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "audience-matrix",
  title: "Audience Matrix",
  subtitle: "Geo, Devices, Traffic, & Sharing",
  category: "community",
  defaultSize: "full",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(31),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "bridge-efficiency",
  title: "Bridge Efficiency",
  subtitle: "Impression to Interaction Funnel",
  category: "analytics",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(32),
  dependency: ["youtube_analytics_v2"],
  status: "ready",
 },
 {
  id: "ask-me",
  title: "Ask Me",
  subtitle: "AI Q&A Chat",
  category: "ai",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "xtall",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(33),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "daily-oracle",
  title: "Daily Oracle",
  subtitle: "Strategic Advice",
  category: "ai",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "xtall",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(34),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "flight-check",
  title: "Upload Flight Check",
  subtitle: "Pre-publish checklist",
  category: "creation",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(35),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "image-generator",
  title: "Image Generator",
  subtitle: "Thumbnail + end screen image generation",
  category: "creation",
  defaultSize: "half",
  minSize: "third",
  maxSize: "full",
  defaultHeight: "xtall",
  minHeight: "medium",
  maxHeight: "massive",
  ...getDashboardWidgetPaletteColors(36),
  dependency: ["gemini_api"],
  status: "ready",
 },
 {
  id: "data-edit",
  title: "Video Manager",
  subtitle: "Quick Metadata Editor",
  category: "creation",
  defaultSize: "half",
  minSize: "third",
  maxSize: "full",
  defaultHeight: "xtall",
  minHeight: "medium",
  maxHeight: "massive",
  ...getDashboardWidgetPaletteColors(37),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "title-rewriter",
  title: "Title Rewriter",
  subtitle: "AI title alternatives",
  category: "creation",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(38),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "retention-sim",
  title: "Retention Simulator",
  subtitle: "Analyze danger zones",
  category: "analytics",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(39),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "upload-scheduler",
  title: "Upload Scheduler",
  subtitle: "7-day content planner",
  category: "creation",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(40),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "hashtag-analyzer",
  title: "Hashtag Analyzer",
  subtitle: "Tag reach and competition",
  category: "analytics",
  defaultSize: "third",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(41),
  dependency: ["none"],
  status: "ready",
 },
 {
  id: "burnout-monitor",
  title: "Burnout Monitor",
  subtitle: "Health and pacing tracker",
  category: "system",
  defaultSize: "half",
  minSize: "quarter",
  maxSize: "full",
  defaultHeight: "medium",
  minHeight: "short",
  maxHeight: "xtall",
  ...getDashboardWidgetPaletteColors(42),
  dependency: ["none"],
  status: "ready",
 },
  {
   id: "collab-matchmaker",
   title: "Collab Matchmaker",
   subtitle: "Find peers and generate pitches",
   category: "community",
   defaultSize: "half",
   minSize: "quarter",
   maxSize: "full",
   defaultHeight: "medium",
   minHeight: "short",
   maxHeight: "xtall",
   ...getDashboardWidgetPaletteColors(43),
   dependency: ["gemini_api", "youtube_data_v3"],
   status: "ready",
  },
  {
    id: "ai-journal",
    title: "AI Journal",
    subtitle: "Creator vision & the pulse",
    category: "ai",
    defaultSize: "third",
    minSize: "quarter",
    maxSize: "full",
    defaultHeight: "xtall",
    minHeight: "short",
    maxHeight: "xtall",
    ...getDashboardWidgetPaletteColors(44),
    dependency: ["gemini_api"],
    status: "ready",
  },
  {
    id: "brain-hub",
    title: "Brain Hub",
    subtitle: "AI Memory & OODA Directive",
    category: "ai",
    defaultSize: "half",
    minSize: "quarter",
    maxSize: "full",
    defaultHeight: "xtall",
    minHeight: "short",
    maxHeight: "xtall",
    ...getDashboardWidgetPaletteColors(45),
    dependency: ["none"],
    status: "ready",
  },
]

const prioritizedOrder = [
  // Row 1 — Top shelf (all 1/3)
  "kpi-cluster",
  "community-post",
  "comment-replier",
  // Row 2 — Instrument panel (all 1/4)
  "consistency-heatmap",
  "realtime-performance",
  "goals-tracker",
  "keyword-engine",
  // Row 3 — AI zone (all 1/3)
  "daily-oracle",
  "ask-me",
  "ai-journal",
  // Row 4 — Creation tools (all 1/2)
  "data-edit",
  "brain-hub",
  // Remaining — analytics & tools
  "revenue-chart",
  "traffic-sources",
  "recent-uploads",
  "top-performer",
  "reach-funnel",
  "alerts-feed",
  "channel-overview",
  "thumb-ai",
  "mini-calendar",
  "task-stack",
  "system-micro-stack",
  "shorts-vs-long",
  "collab-matchmaker",
 ];

export const DEFAULT_DASHBOARD_WIDGET_ORDER = [
  ...prioritizedOrder,
  ...DASHBOARD_WIDGET_REGISTRY.map((widget) => widget.id).filter(id => !prioritizedOrder.includes(id))
]

export const DASHBOARD_WIDGET_BY_ID = Object.fromEntries(
 DASHBOARD_WIDGET_REGISTRY.map((widget) => [widget.id, widget]),
)
