import React from 'react';
import type {VtE1Clip} from '../../shared/vtE1TimelineContract';
import type {TemplateDefinition,TemplateElement} from '../core/schema';
type DesignClip=VtE1Clip&{templateDefinition?:TemplateDefinition};
export interface TemplateElementSelection{clipId:string;elementId:string}
export interface TemplateCanvasRendererProps{clips:VtE1Clip[];playheadSec:number;selected?:TemplateElementSelection|null;onSelectElement?:(selection:TemplateElementSelection)=>void}
const elementStyle=(e:TemplateElement,t:TemplateDefinition):React.CSSProperties=>({position:'absolute',left:`${e.x/t.width*100}%`,top:`${e.y/t.height*100}%`,width:`${e.width/t.width*100}%`,height:`${e.height/t.height*100}%`,opacity:e.opacity??1,rotate:e.rotation?`${e.rotation}deg`:undefined,boxSizing:'border-box'});
export const TemplateCanvasRenderer:React.FC<TemplateCanvasRendererProps>=({clips,playheadSec,selected,onSelectElement})=>{const active=clips.filter(c=>playheadSec>=c.start&&playheadSec<c.end&&(c as DesignClip).templateDefinition);return <div data-viewtube-template-canvas style={{position:'absolute',inset:0,pointerEvents:onSelectElement?'auto':'none'}}>{active.map(clip=>{const t=(clip as DesignClip).templateDefinition!;return <div key={clip.id} style={{position:'absolute',inset:0,background:t.background??'transparent',overflow:'hidden'}}>{t.elements.map(e=><Element key={e.id} element={e} template={t} selected={selected?.clipId===clip.id&&selected.elementId===e.id} onSelect={()=>onSelectElement?.({clipId:clip.id,elementId:e.id})}/>)}</div>})}</div>};
const Element:React.FC<{element:TemplateElement;template:TemplateDefinition;selected:boolean;onSelect:()=>void}>=({element:e,template:t,selected,onSelect})=>{const outline=selected?{outline:'3px solid #36E0F6',outlineOffset:2}:{};if(e.type==='text')return <div onPointerDown={ev=>{ev.stopPropagation();onSelect()}} style={{...elementStyle(e,t),...outline,fontFamily:e.fontFamily??'Arial, sans-serif',fontSize:`clamp(10px, ${(e.fontSize??48)/t.width*100}vw, ${e.fontSize??48}px)`,fontWeight:e.fontWeight??900,lineHeight:.95,color:e.fill??'#171717',whiteSpace:'pre-wrap',cursor:e.editable?'pointer':'default'}}>{e.text}</div>;if(e.type==='svg'&&e.svg)return <div onPointerDown={ev=>{ev.stopPropagation();onSelect()}} style={{...elementStyle(e,t),...outline,cursor:e.editable?'pointer':'default'}}><img alt="" draggable={false} src={`data:image/svg+xml;charset=utf-8,${encodeURIComponent(e.svg)}`} style={{width:'100%',height:'100%',display:'block',pointerEvents:'none'}}/></div>;return null};
