import React from "react"
import { AlertTriangle, CalendarRange, CheckCircle2, Clock3, Layers3, Scale } from "lucide-react"
import InternalSuperToolWorkbench, {
 type InternalWorkbenchConfig,
} from "./supertools/InternalSuperToolWorkbench"

const config: InternalWorkbenchConfig = {
 toolId: "publishing-schedule-architect",
 toolNumber: "06",
 title: "Publishing Schedule Architect",
 subtitle:
  "Balance cadence, backlog, launch windows, and channel energy so publishing discipline becomes a system instead of a guess.",
 railTitle: "Publishing Cadence Layer",
 railSubtitle: "Calendar pressure, backlog balancing, launch windows, cadence guardrails",
 railNote:
  "This lane may merge into Project Command at v1, but it still needs explicit scheduling logic and persisted handoffs.",
 accentClassName: "bg-[#FFEA5A]",
 heroShadowClassName: "shadow-[12px_12px_0px_0px_#FFEA5A]",
 modeLabel: "Scheduling mode",
 sourceLabel: "Backlog or publish target",
 sourcePlaceholder: "Week, month, backlog slice, or launch window",
 objectiveLabel: "Cadence objective",
 objectivePlaceholder: "Increase consistency, protect quality, smooth backlog, or sequence campaigns",
 notesLabel: "Timing constraints",
 notesPlaceholder: "Deadlines, sponsor windows, creator capacity, release timing, and dependencies",
 modules: [
  {
   id: "cadence-planner",
   title: "Cadence Planner",
   body: "Defines the publishing rhythm that the channel can actually sustain rather than the one it merely wishes it could sustain.",
   purpose: "Define the publishing rhythm the channel can actually sustain rather than the one it merely wishes it could sustain.",
   controls: ["cadence", "capacity", "format mix", "quality gate"],
   outputKind: "cadence rule set",
   integrations: ["Project Command", "Brain priorities", "Analytics"],
   selfImprovementSignal: "records cadence assumptions that need validation after publishing",
   tone: "bg-[#FFEA5A]",
   icon: Clock3,
  },
  {
   id: "backlog-balancer",
   title: "Backlog Balancer",
   body: "Keeps shorts, long-form, series episodes, and experiments from cannibalizing each other.",
   purpose: "Keep shorts, long-form, series episodes, and experiments from cannibalizing each other.",
   controls: ["format ratio", "ready work", "blocked work", "priority"],
   outputKind: "balanced backlog order",
   integrations: ["Project Command", "Series Generator", "Workflow Chain"],
   selfImprovementSignal: "tracks when backlog priority changes because capacity was wrong",
   tone: "bg-[#00F0FF]",
   icon: Scale,
  },
  {
   id: "campaign-window",
   title: "Campaign Window",
   body: "Places each publish candidate in a realistic timing lane with explicit readiness checks.",
   purpose: "Place each publish candidate in a realistic timing lane with explicit readiness and campaign checks.",
   controls: ["window", "sponsor pressure", "seasonality", "launch spacing"],
   outputKind: "campaign timing map",
   integrations: ["Project Command", "Packaging Lab", "Audience Loop"],
   selfImprovementSignal: "records timing pressure and skipped campaign assumptions",
   tone: "bg-[#CCFF00]",
   icon: CalendarRange,
  },
  {
   id: "publish-readiness",
   title: "Publish Readiness",
   body: "Checks assets, packaging, edit state, metadata, follow-up, and owner readiness before a date is treated as real.",
   purpose: "Check assets, packaging, edit state, metadata, follow-up, and owner readiness before a date is treated as real.",
   controls: ["asset state", "metadata state", "edit state", "follow-up"],
   outputKind: "publish readiness gate",
   integrations: ["Vault", "VT_E1", "Project Command"],
   selfImprovementSignal: "records readiness failures and which gate caught them",
   tone: "bg-[#FF4FD8] text-white",
   icon: CheckCircle2,
  },
 {
  id: "recovery-plan",
   title: "Recovery Plan",
   body: "Turns missed cadence, delayed projects, or overloaded backlog into a realistic recovery sequence.",
   purpose: "Turn missed cadence, delayed projects, or overloaded backlog into a realistic recovery sequence.",
   controls: ["missed date", "recovery window", "scope cut", "next publish"],
   outputKind: "schedule recovery packet",
   integrations: ["Brain Command", "Workflow Chain", "Project Command"],
   selfImprovementSignal: "learns which recovery moves reduce future schedule drift",
   tone: "bg-[#FFEA5A]",
  icon: AlertTriangle,
  },
 ],
 prototype: {
  toolId: "publishing-schedule-architect",
  title: "Publishing Architect Prototype",
  description: "Early workspace for backlog priority, calendar windows, campaign pressure, readiness, and recovery.",
  lanes: [
   { id: "backlog-queue", title: "Backlog Queue", description: "Ready, blocked, and candidate work", tone: "bg-[#FFEA5A]" },
   { id: "calendar-window", title: "Calendar Window", description: "Publish timing and spacing", tone: "bg-[#00F0FF]" },
   { id: "campaign-lane", title: "Campaign Lane", description: "Sponsor and seasonal pressure", tone: "bg-[#CCFF00]" },
   { id: "readiness-recovery", title: "Readiness / Recovery", description: "Quality gates and fallback moves", tone: "bg-[#FF4FD8] text-white" },
  ],
  cards: [
   {
    id: "shorts-backlog-balance",
    laneId: "backlog-queue",
    title: "Shorts backlog balance",
    summary: "Prevent shorts extraction work from crowding out launch-critical long-form tasks.",
    status: "active",
    priority: "high",
    chips: ["format ratio", "priority"],
    controls: ["ready work", "blocked work"],
    output: "balanced backlog order",
    integrations: ["Project Command", "Shorts Studio"],
    handoffTarget: "Project Command",
   },
   {
    id: "calendar-next-week",
    laneId: "calendar-window",
    title: "Next-week publish window",
    summary: "Place the next upload only after packaging, edit state, and follow-up are known.",
    status: "queued",
    priority: "medium",
    chips: ["publish window", "spacing"],
    controls: ["date range", "quality gate"],
    output: "campaign timing map",
    integrations: ["Project Command"],
    handoffTarget: "Launch Readiness",
   },
   {
    id: "campaign-sponsor-window",
    laneId: "campaign-lane",
    title: "Sponsor campaign pressure",
    summary: "Sequence sponsor due dates without hiding review and revision risk.",
    status: "blocked",
    priority: "urgent",
    blocker: "Approval window not confirmed",
    chips: ["sponsor", "seasonality"],
    controls: ["launch spacing", "sponsor pressure"],
    output: "campaign timing map",
    integrations: ["Workflow Chain"],
    handoffTarget: "Brain Command",
   },
   {
    id: "cadence-recovery",
    laneId: "readiness-recovery",
    title: "Cadence recovery plan",
    summary: "Cut scope and recover the next publish without lowering quality gates.",
    status: "ready",
    priority: "high",
    chips: ["scope cut", "recovery"],
    controls: ["missed date", "next publish"],
    output: "schedule recovery packet",
    integrations: ["Brain Command", "Project Command"],
    handoffTarget: "Workflow Chain",
   },
  ],
  controls: ["select publish target", "move timing lane", "mark blocker", "mark ready"],
  evidence: ["backlog state", "deadline", "capacity", "readiness gate"],
  handoffTargets: ["Project Command", "Brain Command", "Workflow Chain"],
 },
 modes: [
  { id: "weekly", label: "Weekly Cadence", description: "Protect a stable weekly sequence without overloading production." },
  { id: "campaign", label: "Campaign Window", description: "Sequence a release cluster around launches, sponsors, or seasonal moments." },
  { id: "recovery", label: "Cadence Recovery", description: "Rebuild consistency after backlog drift or missed releases." },
 ],
 metrics: [
  { label: "Owns", value: "Cadence, backlog, launch timing", icon: CalendarRange, tone: "bg-[#FFEA5A]" },
  { label: "Feeds", value: "Projects + publish handoff", icon: Layers3, tone: "bg-[#CCFF00]" },
  { label: "Protects", value: "Quality from schedule chaos", icon: Scale, tone: "bg-[#00F0FF]" },
  { label: "Boundary", value: "Likely embedded at v1", icon: Clock3, tone: "bg-[#FF4FD8] text-white" },
 ],
 sisterToolIds: [
  "publishing-schedule-architect",
  "project-command-kanban",
  "series-and-theme-generator",
  "brain-command-center",
  "creator-canvas-os",
 ],
 outputLanes: [
  { label: "Input", value: "Backlog, deadlines, cadence goals, creator capacity" },
  { label: "Output", value: "Publish windows, queue order, cadence guardrails, launch notes" },
  { label: "Handoff", value: "Project board, Brain priorities, follow-up workflows" },
 ],
 buildPacket: ({ source, objective, notes, mode, brainContext, workflowCount }) => ({
  title: source || "Publishing Schedule Packet",
  summary: `Built ${mode.label.toLowerCase()} schedule packet for ${source || "a backlog window"} with persisted launch-order and cadence decisions.`,
  packet: {
   ownership: "cadence planning, backlog balancing, launch sequence",
   mode: mode.label,
   source: source || "Untitled backlog window",
   objective: objective || "Make publishing cadence durable and strategically sequenced",
   creatorNotes: notes || "No extra scheduling notes provided.",
   scheduleRules: [
    "sequence work by readiness, not only desire",
    "protect repeatable cadence before overfilling the calendar",
    "make sponsor or seasonal pressure explicit instead of implicit",
   ],
   brainSignals: {
    strategicAdvice: brainContext?.strategicAdvice || null,
    contextBlock: brainContext?.toolContextPack?.summary || null,
   },
   deliverables: [
    "cadence rule set",
    "backlog order",
    "launch window map",
    "readiness warnings",
   ],
   workflowCount,
  },
  workflowTitle: `${source || "Publishing"} cadence chain`,
  workflowGoal: "Turn backlog and launch pressure into a realistic publishing sequence that the project system can execute.",
  workflowSteps: [
   {
    title: "Confirm project readiness",
    surface: "projects",
    toolId: "project-command-kanban",
    details: "Check which deliverables and blockers already exist.",
   },
   {
    title: "Place publish windows",
    surface: "projects",
    toolId: "publishing-schedule-architect",
    details: "Assign publish targets, queue order, and launch spacing.",
   },
   {
    title: "Adjust series timing",
    surface: "projects",
    toolId: "series-and-theme-generator",
    details: "Ensure recurring series logic matches the planned cadence.",
   },
   {
    title: "Emit schedule pressure",
    surface: "brain",
    toolId: "brain-command-center",
    details: "Send cadence risks and missed timing pressure back to the Brain.",
   },
  ],
 }),
}

const PublishingScheduleArchitect: React.FC<{ embedded?: boolean }> = ({
 embedded = false,
}) => <InternalSuperToolWorkbench config={config} embedded={embedded} />

export default PublishingScheduleArchitect
