import fs from 'fs';
import path from 'path';

const parseCSV = (text) => {
  try {
    const lines = text.split('\n').filter((line) => line.trim());
    if (lines.length < 2) return [];

    const parseLine = (line) => {
      const result = [];
      let current = '';
      let inQuotes = false;

      for (let i = 0; i < line.length; i += 1) {
        const char = line[i];
        if (char === '"') {
          inQuotes = !inQuotes;
        } else if (char === ',' && !inQuotes) {
          result.push(current);
          current = '';
        } else {
          current += char;
        }
      }
      result.push(current);
      return result.map((value) => value.trim().replace(/^"|"$/g, ''));
    };

    const headers = parseLine(lines[0]);

    return lines.slice(1).map((line) => {
      const values = parseLine(line);
      const row = {};
      headers.forEach((header, index) => {
        const rawValue = values[index];
        if (rawValue === undefined) return;
        const numericCandidate = rawValue.replace(/%/g, '').replace(/,/g, '');
        if (numericCandidate !== '' && !Number.isNaN(Number(numericCandidate))) {
          row[header] = Number(numericCandidate);
        } else {
          row[header] = rawValue;
        }
      });
      return row;
    });
  } catch {
    return [];
  }
};

const csvFilesToLoad = [
  {
    path: '/Users/cwb/Downloads/Content 2022-05-06_2026-05-15 The Motion Visual History (3)/Table data.csv',
    name: 'content_channel_all_table_data.csv',
    tag: 'mixed',
    detectedCategory: 'content_channel_all',
    exportKind: 'table_data'
  },
  {
    path: '/Users/cwb/Downloads/traffic/Table data.csv',
    name: 'traffic_overview_table_data.csv',
    tag: 'traffic',
    detectedCategory: 'traffic_overview',
    exportKind: 'totals'
  },
  {
    path: '/Users/cwb/Downloads/traffic/Table data copy.csv',
    name: 'traffic_external_table_data.csv',
    tag: 'traffic',
    detectedCategory: 'traffic_external',
    exportKind: 'table_data'
  },
  {
    path: '/Users/cwb/Downloads/traffic/Table data copy 2.csv',
    name: 'traffic_youtube_search_table_data.csv',
    tag: 'traffic',
    detectedCategory: 'traffic_youtube_search',
    exportKind: 'table_data'
  },
  {
    path: '/Users/cwb/Downloads/traffic/Table data copy 3.csv',
    name: 'traffic_suggested_videos_table_data.csv',
    tag: 'traffic',
    detectedCategory: 'traffic_suggested_videos',
    exportKind: 'table_data'
  },
  {
    path: '/Users/cwb/Downloads/traffic/Table data copy 4.csv',
    name: 'traffic_shorts_feed_table_data.csv',
    tag: 'traffic',
    detectedCategory: 'traffic_shorts_feed',
    exportKind: 'table_data'
  },
  {
    path: '/Users/cwb/Downloads/files/Geography 2022-05-06_2026-05-17 The Motion Visual History (1)/Table data.csv',
    name: 'geography_country_table_data.csv',
    tag: 'geo',
    detectedCategory: 'geography_country',
    exportKind: 'table_data'
  }
];

const preloadedFiles = [];

csvFilesToLoad.forEach((item) => {
  console.log(`Processing: ${item.path}`);
  if (!fs.existsSync(item.path)) {
    console.error(`File not found: ${item.path}`);
    process.exit(1);
  }
  const content = fs.readFileSync(item.path, 'utf8');
  const data = parseCSV(content);
  const stats = fs.statSync(item.path);

  preloadedFiles.push({
    id: `preloaded-${item.detectedCategory}`,
    name: item.name,
    tag: item.tag,
    byteSize: stats.size,
    data: data,
    detectedCategory: item.detectedCategory,
    exportKind: item.exportKind,
    detectionConfidence: 'high',
    signatureId: `${item.detectedCategory}_preloaded`
  });
});

const fileContent = `// This file is auto-generated by generate_preloaded_csv.js. Do not edit directly.
import type { CsvFileWithTag } from '../types';

export const PRELOADED_CSV_FILES: CsvFileWithTag[] = ${JSON.stringify(preloadedFiles, null, 2)};
`;

const outputPath = './src/services/preloadedCsvData.ts';
fs.writeFileSync(outputPath, fileContent, 'utf8');
console.log(`Successfully generated: ${outputPath}`);
