#!/usr/bin/env node
/**
 * herald-sync — distribute the agent contract from agent/ to every tool.
 *
 *   node scripts/herald-sync.mjs           write targets
 *   node scripts/herald-sync.mjs --check   exit 1 on drift, write nothing
 *
 * Sources live under agent/. Targets are generated and must never be hand-edited;
 * that is the drift this script exists to prevent.
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const CHECK = process.argv.includes('--check');
const cfg = JSON.parse(fs.readFileSync(path.join(ROOT, 'agent/targets.json'), 'utf8'));

const BANNER_PREFIX = 'GENERATED by scripts/herald-sync.mjs from';
const drift = [];
const wrote = [];

const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const banner = (source) =>
  `<!-- ${BANNER_PREFIX} ${source} — do not edit; run \`node scripts/herald-sync.mjs\` -->`;

/** Split leading YAML frontmatter so a banner never lands above it. */
function splitFrontmatter(text) {
  if (!text.startsWith('---\n')) return { front: '', body: text };
  const end = text.indexOf('\n---\n', 4);
  if (end === -1) return { front: '', body: text };
  return { front: text.slice(0, end + 5), body: text.slice(end + 5) };
}

/**
 * A SKILL.md with no `name`/`description` frontmatter is never loaded as a skill, and
 * banner-prefixing it makes the banner masquerade as its description. Fail loudly instead.
 */
const invalid = [];
function validateSkill(relPath, text) {
  const { front } = splitFrontmatter(text);
  if (!front) return invalid.push(`${relPath}: missing YAML frontmatter`);
  if (!/^name:\s*\S/m.test(front)) return invalid.push(`${relPath}: frontmatter has no \`name\``);
  if (!/^description:\s*\S/m.test(front)) return invalid.push(`${relPath}: frontmatter has no \`description\``);
  const name = front.match(/^name:\s*(\S+)/m)[1];
  const dir = relPath.split('/').slice(-2)[0];
  if (name !== dir) invalid.push(`${relPath}: frontmatter name "${name}" does not match directory "${dir}"`);
}

function withBanner(text, source, extraFront) {
  const { front, body } = splitFrontmatter(text);
  const head = extraFront ?? front;
  return `${head}${head ? '' : ''}${banner(source)}\n\n${body.replace(/^\n+/, '')}`;
}

function mdcFrontmatter(meta) {
  return `---\ndescription: ${meta.description}\nalwaysApply: ${meta.alwaysApply}\n---\n`;
}

/** Emit one file, or record drift under --check. */
function emit(targetPath, content) {
  const abs = path.join(ROOT, targetPath);
  const existing = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
  if (existing === content) return;
  if (CHECK) {
    drift.push(existing === null ? `${targetPath} (missing)` : `${targetPath} (differs)`);
    return;
  }
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content);
  wrote.push(targetPath);
}

/** Recursively list files under a directory, relative to it. */
function walk(dir, base = dir) {
  const out = [];
  for (const entry of fs.readdirSync(path.join(ROOT, dir), { withFileTypes: true })) {
    const rel = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(rel, base));
    else out.push(path.relative(base, rel));
  }
  return out;
}

// ---- brief: one authored file, several tool-specific filenames -------------
const briefSource = cfg.brief.source;
const briefText = read(briefSource);
for (const t of cfg.brief.targets) {
  const content = t.mdc
    ? withBanner(briefText, briefSource, mdcFrontmatter(t.mdc))
    : withBanner(briefText, briefSource);
  emit(t.path, content);
}

// ---- skills: mirrored verbatim, with a banner after any frontmatter --------
const skillSource = cfg.skills.source;
const skillFiles = walk(skillSource);

for (const rel of skillFiles) {
  if (path.basename(rel) === 'SKILL.md') validateSkill(path.join(skillSource, rel), read(path.join(skillSource, rel)));
}
if (invalid.length) {
  console.error(`herald-sync: ${invalid.length} invalid skill source(s) — nothing written\n`);
  for (const i of invalid) console.error(`  ${i}`);
  process.exit(1);
}

for (const t of cfg.skills.targets) {
  for (const rel of skillFiles) {
    const src = path.join(skillSource, rel);
    const text = read(src);
    const content = rel.endsWith('.md') ? withBanner(text, src) : text;
    emit(path.join(t.path, rel), content);
  }
  // stale targets: files present downstream that no longer exist upstream
  const tAbs = path.join(ROOT, t.path);
  if (fs.existsSync(tAbs)) {
    for (const rel of walk(t.path)) {
      if (skillFiles.includes(rel)) continue;
      const stale = path.join(t.path, rel);
      if (CHECK) drift.push(`${stale} (stale — no longer in ${skillSource})`);
      else { fs.rmSync(path.join(ROOT, stale)); wrote.push(`${stale} (removed)`); }
    }
  }
}

// ---- report ---------------------------------------------------------------
if (CHECK) {
  if (drift.length) {
    console.error(`herald-sync: ${drift.length} target(s) out of sync with agent/\n`);
    for (const d of drift) console.error(`  ${d}`);
    console.error('\nRun: node scripts/herald-sync.mjs');
    process.exit(1);
  }
  console.log(`herald-sync: all targets in sync (${cfg.brief.targets.length} brief, ${skillFiles.length} skill files x ${cfg.skills.targets.length} targets)`);
} else {
  console.log(wrote.length ? `herald-sync: wrote ${wrote.length} file(s)` : 'herald-sync: already in sync');
  for (const w of wrote.slice(0, 12)) console.log(`  ${w}`);
  if (wrote.length > 12) console.log(`  … and ${wrote.length - 12} more`);
}
