/** PanelBodies — immediately useful mobile editor panels. */
import React from 'react';
import {EditorStore,Tool} from '../state/editorState';
import type {VtE1Transition} from '../../../../shared/vtE1TimelineContract';
import {TemplateLibraryPanel} from './TemplateLibraryPanel';
interface PanelProps{store:EditorStore}
const row:React.CSSProperties={display:'flex',gap:8,marginBottom:10,alignItems:'center'};
const btn:React.CSSProperties={flex:1,padding:'10px 12px',borderRadius:10,background:'#1e293b',border:'1px solid #334155',color:'#e2e8f0',fontSize:12,fontWeight:800,textTransform:'uppercase',letterSpacing:.4,cursor:'pointer'};
const primary:React.CSSProperties={...btn,background:'#22d3ee',color:'#0f172a',border:'none'};const label:React.CSSProperties={fontSize:11,color:'#94a3b8',textTransform:'uppercase',letterSpacing:.5,marginBottom:6};
const SelectPanel:React.FC<PanelProps>=({store})=>{const{selectedClips,dispatch}=store;if(!selectedClips.length)return <div style={{opacity:.6,fontSize:13}}>Tap a clip in the timeline to select it. Long-press for more actions.</div>;return <div><div style={label}>Selected · {selectedClips.length}</div>{selectedClips.map(c=><div key={c.id} style={{padding:8,background:'#1e293b',borderRadius:8,fontSize:12,marginBottom:6}}><b>{String(c.id)}</b><div style={{opacity:.7}}>{c.start.toFixed(2)}s → {c.end.toFixed(2)}s</div></div>)}<div style={{...row,marginTop:12}}><button style={btn} onClick={()=>selectedClips.forEach(c=>dispatch({type:'duplicateClip',id:c.id}))}>Duplicate</button><button style={{...btn,color:'#f87171'}} onClick={()=>dispatch({type:'deleteClips',ids:selectedClips.map(c=>c.id)})}>Delete</button></div></div>};
const TrimPanel:React.FC<PanelProps>=({store})=>{const{selectedClips,dispatch,state}=store,clip=selectedClips[0];if(!clip)return <div style={{opacity:.6}}>Select a clip to trim.</div>;return <div><div style={label}>Trim start</div><input type="range" min={0} max={clip.end-.1} step={.05} value={clip.start} onChange={e=>dispatch({type:'trimClip',id:clip.id,side:'left',sec:Number(e.target.value)})} style={{width:'100%'}}/><div style={{...label,marginTop:12}}>Trim end</div><input type="range" min={clip.start+.1} max={state.project.durationSec} step={.05} value={clip.end} onChange={e=>dispatch({type:'trimClip',id:clip.id,side:'right',sec:Number(e.target.value)})} style={{width:'100%'}}/><button style={{...btn,marginTop:14}} onClick={()=>dispatch({type:'splitClipAtPlayhead',id:clip.id})}>Split at playhead</button></div>};
const TextPanel:React.FC<PanelProps>=({store})=>{const{state,dispatch}=store;return <div><div style={label}>Add text</div><input placeholder="Type overlay text…" style={{width:'100%',padding:'10px 12px',borderRadius:10,background:'#1e293b',border:'1px solid #334155',color:'#e2e8f0',fontSize:14}} onKeyDown={e=>{if(e.key!=='Enter')return;const value=e.currentTarget.value.trim();if(!value)return;dispatch({type:'addClip',clip:{id:`text_${Date.now().toString(36)}`,trackId:'t_overlay',start:state.playheadSec,end:state.playheadSec+2,text:value}});e.currentTarget.value=''}}/><div style={{marginTop:6,fontSize:11,opacity:.6}}>Press Return to drop a 2-second title at the playhead.</div></div>};
const AudioPanel:React.FC<PanelProps>=({store})=><div><div style={label}>Tracks</div>{store.state.project.tracks.map(t=><div key={t.id} style={{...row,background:'#1e293b',padding:8,borderRadius:8}}><b style={{flex:1}}>{t.name}</b><button style={{...btn,flex:'none',width:88,background:t.muted?'#ef4444':'#334155'}} onClick={()=>store.dispatch({type:'muteTrack',id:t.id})}>{t.muted?'Muted':'Mute'}</button></div>)}</div>;
const TransitionsPanel:React.FC<PanelProps>=({store})=>{const{selectedClips,state,dispatch}=store,[left,right]=selectedClips.slice(0,2),canAdd=Boolean(left&&right),list=['fade','slide','wipe','iris','flip','clockWipe'];return <div><div style={label}>{canAdd?`Add transition between ${left.id} and ${right.id}`:'Select two adjacent clips to add a transition'}</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:6}}>{list.map(key=><button key={key} disabled={!canAdd} style={{...btn,opacity:canAdd?1:.4}} onClick={()=>{if(!left||!right)return;const transition:VtE1Transition={leftClipId:left.id,rightClipId:right.id,durationSec:.4,nominalSeamSec:(left.end+right.start)/2,id:`${key}_${Date.now().toString(36)}`,presentation:key};dispatch({type:'addTransition',transition})}}>{key}</button>)}</div><div style={{...label,marginTop:14}}>Existing · {(state.project.transitions??[]).length}</div></div>};
const EffectsPanel:React.FC<PanelProps>=()=> <div style={{opacity:.65,fontSize:13}}>Effects panel — color, blur and motion presets.</div>;
const ExportPanel:React.FC<PanelProps>=({store})=><div><div style={label}>Export</div><div style={{background:'#1e293b',padding:12,borderRadius:10,marginBottom:12}}><div style={{fontSize:12,opacity:.7}}>Duration</div><b style={{fontSize:20}}>{store.state.project.durationSec.toFixed(1)}s</b><div style={{fontSize:12,opacity:.7,marginTop:6}}>Clips</div><b style={{fontSize:20}}>{store.state.project.clips.length}</b></div><button style={primary}>Render MP4 (H.264)</button></div>;
export const PanelBodies={select:SelectPanel,trim:TrimPanel,split:TrimPanel,templates:TemplateLibraryPanel,text:TextPanel,audio:AudioPanel,transitions:TransitionsPanel,effects:EffectsPanel,export:ExportPanel} satisfies Record<Tool,React.FC<PanelProps>>;
export function renderPanelBody(tool:Tool,store:EditorStore){const Body=PanelBodies[tool];return <Body store={store}/>}
