/** Mobile tool bodies backed by the shared editor store. */
import React from'react';import{EditorStore,Tool}from'../state/editorState';import type{VtE1Transition}from'../../../../shared/vtE1TimelineContract';
interface PanelProps{store:EditorStore}const INK='#248b99',CYAN='#36E0F6',row:React.CSSProperties={display:'flex',gap:5,marginBottom:6,alignItems:'center'},btn:React.CSSProperties={flex:1,minHeight:30,padding:'5px 8px',borderRadius:5,background:'#fff',border:`2px solid ${INK}`,color:'#000',fontSize:9,fontWeight:900,textTransform:'uppercase'},primary={...btn,background:CYAN},label:React.CSSProperties={fontSize:9,fontWeight:900,textTransform:'uppercase',letterSpacing:.6,marginBottom:5},card:React.CSSProperties={border:`2px solid ${INK}`,borderRadius:6,background:'#fff',padding:8,marginBottom:6,boxShadow:'2px 2px 0 rgba(54,224,246,.22)'};const Card=({name,children}:{name:string;children:React.ReactNode})=><section style={card}><div style={label}>{name}</div>{children}</section>;
const SelectPanel=({store}:PanelProps)=>store.selectedClips.length?<Card name="Selection">{store.selectedClips.map(c=><div key={c.id} style={row}><b style={{flex:1}}>{String(c.id)}</b><button style={btn} onClick={()=>store.dispatch({type:'duplicateClip',id:c.id})}>Dup</button></div>)}</Card>:<Card name="Selection">Select a clip in the timeline.</Card>;
const TrimPanel=({store}:PanelProps)=>{const c=store.selectedClips[0];return!c?<Card name="Trim">Select a clip.</Card>:<Card name="Trim"><div style={label}>Start {c.start.toFixed(2)}s</div><input type="range" min={0} max={c.end-.1} step={.05} value={c.start} onChange={e=>store.dispatch({type:'trimClip',id:c.id,side:'left',sec:+e.target.value})} style={{width:'100%'}}/><div style={label}>End {c.end.toFixed(2)}s</div><input type="range" min={c.start+.1} max={store.state.project.durationSec} step={.05} value={c.end} onChange={e=>store.dispatch({type:'trimClip',id:c.id,side:'right',sec:+e.target.value})} style={{width:'100%'}}/></Card>};
const TextPanel=({store}:PanelProps)=><><Card name="Add Text"><input placeholder="Type overlay text and press Return" style={{width:'100%',height:32,border:`2px solid ${INK}`,borderRadius:5,padding:'0 7px',boxSizing:'border-box'}} onKeyDown={e=>{if(e.key!=='Enter')return;const v=e.currentTarget.value.trim();if(!v)return;store.dispatch({type:'addClip',clip:{id:`text_${Date.now().toString(36)}`,trackId:'t_overlay',start:store.state.playheadSec,end:store.state.playheadSec+2,text:v}});e.currentTarget.value=''}}/></Card><Card name="Text Tools"><div style={{fontSize:10,fontWeight:800}}>Content is active. Typography, alignment, appearance and animation remain capability-gated until their shared clip fields are finalized.</div></Card></>;
const AudioPanel=({store}:PanelProps)=><><Card name="Audio Tracks">{store.state.project.tracks.filter(t=>t.kind==='audio').map(t=><div key={t.id} style={row}><b style={{flex:1}}>{t.name}</b><button style={{...btn,background:t.muted?'#FA618A':'#fff'}} onClick={()=>store.dispatch({type:'muteTrack',id:t.id})}>{t.muted?'Unmute':'Mute'}</button></div>)}</Card><Card name="Audio Tools"><div style={{fontSize:10,fontWeight:800}}>Track mute is active. Volume, fades and ducking remain disabled until connected to the shared audio model.</div></Card></>;
const TransitionsPanel=({store}:PanelProps)=>{const[left,right]=store.selectedClips.slice(0,2),can=!!(left&&right),list=[['fade','Fade'],['slide','Slide'],['wipe','Wipe'],['iris','Iris'],['flip','Flip'],['clockWipe','Clock']];return <><Card name="Add Transition"><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:5}}>{list.map(([key,name])=><button key={key} disabled={!can} style={{...btn,opacity:can?1:.4}} onClick={()=>{if(!can)return;const transition:VtE1Transition={leftClipId:left.id,rightClipId:right.id,durationSec:.4,nominalSeamSec:(left.end+right.start)/2,id:`${key}_${Date.now().toString(36)}`,presentation:key};store.dispatch({type:'addTransition',transition})}}>{name}</button>)}</div></Card><Card name="Existing">{(store.state.project.transitions??[]).map((t,i)=>{const id=String((t as{id?:unknown}).id??`${t.leftClipId}-${t.rightClipId}-${i}`);return <div key={id} style={row}><button style={{...btn,textAlign:'left'}} onClick={()=>store.dispatch({type:'selectTransition',id})}>{String((t as{presentation?:unknown}).presentation??'Transition')}</button><button style={{...btn,flex:'0 0 66px',background:'#FA618A'}} onClick={()=>store.dispatch({type:'removeTransition',id})}>Remove</button></div>})}</Card></>};
const EffectsPanel=({store}:PanelProps)=>{const c=store.selectedClips[0];return <><Card name="Effects"><div style={{fontSize:10,fontWeight:800}}>{c?`Selected: ${c.id}`:'Select a clip to edit effects.'}</div></Card><Card name="Status"><div style={{fontSize:10,fontWeight:800}}>Color, blur and motion blur are intentionally not rendered as fake controls until their engine actions are connected.</div></Card></>};
const ExportPanel=({store}:PanelProps)=><><Card name="Project"><b>{store.state.project.durationSec.toFixed(1)}s · {store.state.project.clips.length} clips</b></Card><Card name="Export"><button style={{...primary,width:'100%'}} disabled>Render MP4 · wiring required</button><div style={{fontSize:9,fontWeight:800,marginTop:5}}>The mobile UI no longer presents an inert render button as functional. This enables when the shared render action is attached.</div></Card></>;
export const PanelBodies={select:SelectPanel,trim:TrimPanel,split:TrimPanel,text:TextPanel,audio:AudioPanel,transitions:TransitionsPanel,effects:EffectsPanel,export:ExportPanel}satisfies Record<Tool,React.FC<PanelProps>>;export function renderPanelBody(tool:Tool,store:EditorStore){const Body=PanelBodies[tool];return <Body store={store}/>}
