/** Compact component-style mobile panel bodies. */
import React from 'react';import {EditorStore,Tool} from '../state/editorState';import type {VtE1Transition} from '../../../../shared/vtE1TimelineContract';
interface PanelProps{store:EditorStore} const INK='#248b99',CYAN='#36E0F6';
const row:React.CSSProperties={display:'flex',gap:5,marginBottom:6,alignItems:'center'};const btn:React.CSSProperties={flex:1,minHeight:30,padding:'5px 7px',borderRadius:5,background:'#fff',border:`2px solid ${INK}`,color:'#000',fontSize:9,fontWeight:900,textTransform:'uppercase'};const primary={...btn,background:CYAN};const label:React.CSSProperties={fontSize:9,color:'#000',fontWeight:900,textTransform:'uppercase',letterSpacing:.5,marginBottom:5};const box:React.CSSProperties={background:'#fff',border:`2px solid ${INK}`,borderRadius:6,padding:7,marginBottom:6};const feature=(items:string[])=><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:4}}>{items.map(x=><button key={x} style={btn}>{x}</button>)}</div>;
const SelectPanel:React.FC<PanelProps>=({store})=>store.selectedClips.length===0?<div style={box}>Tap a clip to select it.</div>:<div><div style={label}>Selected · {store.selectedClips.length}</div>{store.selectedClips.map(c=><div key={c.id} style={box}><b>{String(c.id)}</b><div>{c.start.toFixed(2)}s → {c.end.toFixed(2)}s</div></div>)}<div style={row}><button style={btn} onClick={()=>store.selectedClips.forEach(c=>store.dispatch({type:'duplicateClip',id:c.id}))}>Duplicate</button><button style={btn} onClick={()=>store.dispatch({type:'deleteClips',ids:store.selectedClips.map(c=>c.id)})}>Delete</button></div></div>;
const TrimPanel:React.FC<PanelProps>=({store})=>{const clip=store.selectedClips[0];if(!clip)return <div style={box}>Select a clip to trim.</div>;return <div><div style={label}>Trim start</div><input type="range" min={0} max={clip.end-.1} step={.05} value={clip.start} onChange={e=>store.dispatch({type:'trimClip',id:clip.id,side:'left',sec:Number(e.target.value)})} style={{width:'100%'}}/><div style={label}>Trim end</div><input type="range" min={clip.start+.1} max={store.state.project.durationSec} step={.05} value={clip.end} onChange={e=>store.dispatch({type:'trimClip',id:clip.id,side:'right',sec:Number(e.target.value)})} style={{width:'100%'}}/><button style={btn} onClick={()=>store.dispatch({type:'splitClipAtPlayhead',id:clip.id})}>Split at playhead</button></div>};
const TextPanel:React.FC<PanelProps>=({store})=><div><div style={label}>Add text</div><input placeholder="Type overlay text…" style={{...box,width:'100%',height:34,boxSizing:'border-box'}} onKeyDown={e=>{if(e.key==='Enter'){const v=e.currentTarget.value.trim();if(v){store.dispatch({type:'addClip',clip:{id:`text_${Date.now().toString(36)}`,trackId:'t_overlay',start:store.state.playheadSec,end:store.state.playheadSec+2,text:v}});e.currentTarget.value=''}}}}/><div style={box}>{feature(['Font','Size','Weight','Align','Color','Stroke','Shadow','Tracking','Leading','Animate','Preset','Style'])}</div></div>;
const AudioPanel:React.FC<PanelProps>=({store})=><div><div style={label}>Tracks</div>{store.state.project.tracks.map(t=><div key={t.id} style={{...box,...row}}><b style={{flex:1}}>{t.name}</b><button style={btn} onClick={()=>store.dispatch({type:'muteTrack',id:t.id})}>{t.muted?'Unmute':'Mute'}</button></div>)}<div style={box}>{feature(['Volume','Fade in','Fade out','Pan','EQ','Denoise','Normalize','Duck','Voice','Music','SFX','Waveform'])}</div></div>;
const TransitionsPanel:React.FC<PanelProps>=({store})=>{const [left,right]=store.selectedClips.slice(0,2);const list=['fade','slide','wipe','iris','flip','clockWipe'];return <div><div style={label}>{left&&right?'Choose transition':'Select two adjacent clips'}</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:4}}>{list.map(k=><button key={k} disabled={!left||!right} style={btn} onClick={()=>{if(left&&right){const transition:VtE1Transition={leftClipId:left.id,rightClipId:right.id,durationSec:.4,nominalSeamSec:(left.end+right.start)/2,id:`${k}_${Date.now().toString(36)}`,presentation:k};store.dispatch({type:'addTransition',transition})}}}>{k}</button>)}</div><div style={{...box,marginTop:6}}>{feature(['Duration','Ease','Direction','Preview','Favorites','Custom'])}</div></div>};
const EffectsPanel:React.FC<PanelProps>=()=> <div><div style={box}>{feature(['Color','Exposure','Contrast','Saturation','Temperature','Tint','Blur','Sharpen','Vignette','Grain','Glow','Motion Blur'])}</div><div style={box}>{feature(['Keyframes','Tracking','Mask','Chroma','LUT','Reset'])}</div></div>;
const ExportPanel:React.FC<PanelProps>=({store})=><div><div style={box}><b>{store.state.project.durationSec.toFixed(1)}s</b> · {store.state.project.clips.length} clips</div><div style={box}>{feature(['1080p','4K','H.264','H.265','30 FPS','60 FPS','Quality','Audio','Captions'])}</div><button style={primary}>Render MP4</button></div>;
export const PanelBodies={select:SelectPanel,trim:TrimPanel,split:TrimPanel,text:TextPanel,audio:AudioPanel,transitions:TransitionsPanel,effects:EffectsPanel,export:ExportPanel} satisfies Record<Tool,React.FC<PanelProps>>;export function renderPanelBody(tool:Tool,store:EditorStore){const Body=PanelBodies[tool];return <Body store={store}/>}
