import React, {useMemo, useState} from 'react';
import type {EditorStore} from '../state/editorState';
import {filterTemplateCatalog, templateCatalog} from '../../../editor-design-library/catalog';
import type {TemplateCategory, TemplateDefinition} from '../../../editor-design-library/core/schema';
import {templateToTimelineClip} from '../../../editor-design-library/integration/timelineAdapter';
interface Props {store:EditorStore}
const categories:Array<{label:string;value?:TemplateCategory}>=[{label:'All'},{label:'Backgrounds',value:'background'},{label:'Patterns',value:'pattern'},{label:'Text',value:'text'},{label:'Graphics',value:'graphic'},{label:'Scenes',value:'scene'},{label:'Transitions',value:'transition'}];
const TemplateCard:React.FC<{template:TemplateDefinition;onAdd:()=>void}>=({template,onAdd})=>{const accent=template.palette?.[0]??'#36E0F6';return <button onClick={onAdd} style={{textAlign:'left',padding:0,border:'2px solid #248b99',borderRadius:7,overflow:'hidden',background:'#fff',color:'#171717',boxShadow:`3px 3px 0 ${accent}66`,cursor:'pointer'}}><div style={{aspectRatio:'16 / 9',background:template.background??`${accent}55`,display:'flex',alignItems:'center',justifyContent:'center',padding:8,overflow:'hidden'}}>{template.category==='pattern'&&template.elements[0]?.svg?<img alt="" src={`data:image/svg+xml;charset=utf-8,${encodeURIComponent(template.elements[0].svg)}`} style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<strong style={{fontSize:template.category==='text'?16:11,lineHeight:.95,fontWeight:900,textTransform:'uppercase'}}>{template.elements.find(e=>e.type==='text')?.text??template.name}</strong>}</div><div style={{padding:'6px 7px',borderTop:'2px solid #248b99'}}><div style={{fontSize:9,fontWeight:900,textTransform:'uppercase'}}>{template.name}</div><div style={{fontSize:8,opacity:.55,textTransform:'uppercase'}}>{template.category}</div></div></button>};
export const TemplateLibraryPanel:React.FC<Props>=({store})=>{const[category,setCategory]=useState<TemplateCategory|undefined>();const[query,setQuery]=useState('');const items=useMemo(()=>filterTemplateCatalog(category,query),[category,query]);return <div><div style={{display:'flex',justifyContent:'space-between',alignItems:'baseline',marginBottom:8}}><strong style={{fontSize:12,textTransform:'uppercase'}}>Design Library</strong><span style={{fontSize:9,opacity:.55}}>{templateCatalog.length} templates</span></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search templates…" style={{width:'100%',height:30,padding:'0 8px',borderRadius:5,border:'2px solid #248b99',background:'#fff',color:'#171717',marginBottom:8,boxSizing:'border-box',fontWeight:800}}/><div style={{display:'flex',gap:5,overflowX:'auto',paddingBottom:9}}>{categories.map(c=><button key={c.label} onClick={()=>setCategory(c.value)} style={{flex:'0 0 auto',minHeight:26,padding:'4px 8px',borderRadius:5,border:'2px solid #248b99',background:category===c.value?'#36E0F6':'#fff',color:'#171717',fontSize:8,fontWeight:900,textTransform:'uppercase'}}>{c.label}</button>)}</div><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:8}}>{items.map(template=><TemplateCard key={template.id} template={template} onAdd={()=>store.dispatch({type:'addClip',clip:templateToTimelineClip(template,{startSec:store.state.playheadSec})})}/>)}</div></div>};
